### ISSUE TITLE
Several IPs in configuration

### ISSUE THREAD

**Issue by AntoineLemaire** [lexik/LexikMaintenanceBundle#15]
When I put a array of IPs in the config (like in the documentation), I've got this error : 

```
ErrorException: Warning: strpos() expects parameter 1 to be string, array given in /var/www/symfony2/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/IpUtils.php line 53
```

Here my config.yml :

```
lexik_maintenance:
    authorized:
        ips: ['127.0.0.1', '172.123.10.14']
    driver:      
        ttl: 3600

         # File driver    
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'
        options: {file_path: %kernel.root_dir%/cache/lock}

         # MemCache driver
        class: Lexik\Bundle\MaintenanceBundle\Drivers\MemCacheDriver
        options: {key_name: 'maintenance', host: 127.0.0.1, port: 11211}

        # Database driver:               
        class: 'Lexik\Bundle\MaintenanceBundle\Drivers\DatabaseDriver'

        # Option 1 : for doctrine   
        options: {connection: custom}

        # Option 2 : for dsn, you must have a column ttl type datetime in your table.
        options: {dsn: "mysql:dbname=%database_name%;host=%database_host%", table: maintenance, user: %database_user%, password: %database_password%}
```
