### ISSUE TITLE
response:  code and  status options ignored

### ISSUE THREAD

**Issue by krewetka** [lexik/LexikMaintenanceBundle#36]
In docs there is part about:

```
 #Optional. response code and status of the mantainence page
    response:
        code: 503 
        status: "Service Temporarily Unavailable"    
```
I see   ```$response->setStatusCode($this->http_code, $this->http_status);``` in code but somehow whatever I do I get 

``` 503 Service Unavailable - ServiceUnavailableException ```

to the browser in the end
