### ISSUE TITLE
Nothing happens 

### ISSUE THREAD

**Issue by DonCarlight** [lexik/LexikMaintenanceBundle#63]
Hi all,

I use the bundle with my website from a long time and i didn't have any problem with it until now. 

Now when i activate the maintenance, nothing happens, the site is still accesible and there is no errors in my logs, nothing to help me to know what happens. 

It's sound that happens because of some change i did but which one ? 

Any idea ?

**Comment by vsmihaylovsky** [comment]
Have you tried to clear cache?

**Comment by DonCarlight** [comment]
I found what is causing this error.

I had this listener to know the last activity of my users. When it is, LexikMaintenancebundle doesn't works, when i remove it, it works : 

```
xxxx_ad.security.listener.activity:
        class: XXXX\XXXXBundle\Listener\ActivityListener
        calls:
            - [ setContext, [ @security.context ] ]
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onCoreController }
```

Someone knows how I can use this listener without interfering with LexikMaintenanceBundle ?
